In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df = pd.read_csv("../data/processed/datos_etiquetados.csv")
print(len(df))
df.head(3)

79887

,tweet_id,username,url,text,image,video,date,reply,retweet,like,...,is_rt,rt_by,raw,query_type,scraped_at,event,date_cleansed,date_local,dt_date,label
0,1708973726455181497,@soyingridbeck,https://x.com/soyingridbeck/status/17089737264...,Sólo @SergioMassa y @myriambregman abordaron a...,NaN,NaN,2023-10-02T22:34:22+00:00,0,3,17,...,False,NaN,{'html_tweet': '𝗜𝗻𝗴𝗿𝗶𝗱 𝗕𝗲𝗰𝗸 @soyingridbeck·Oct...,from: @soyingridbeck,2023-10-10T17:43:36.448550+00:00,1er debate,2023-10-02 22:34:22+00:00,2023-10-02 19:34:22-03:00,2023-10-02,[]
1,1708809681924243938,@soyingridbeck,https://x.com/soyingridbeck/status/17088096819...,¿Irse a Marbella en un yate de lujo?,NaN,NaN,2023-10-02T11:42:30+00:00,1,0,0,...,False,NaN,{'html_tweet': '𝗜𝗻𝗴𝗿𝗶𝗱 𝗕𝗲𝗰𝗸 @soyingridbeck·Oct...,from: @soyingridbeck,2023-10-10T17:43:36.612322+00:00,1er debate,2023-10-02 11:42:30+00:00,2023-10-02 08:42:30-03:00,2023-10-02,[]
2,1708810804101853498,@kgalperin,https://x.com/kgalperin/status/170881080410185...,"Me asombra esa interpretación, q expresa muy b...",NaN,NaN,2023-10-02T11:46:58+00:00,0,0,1,...,False,NaN,{'html_tweet': 'Karina Galperin@kgalperin·Oct ...,to: @soyingridbeck,2023-10-10T18:22:43.429345+00:00,1er debate,2023-10-02 11:46:58+00:00,2023-10-02 08:46:58-03:00,2023-10-02,[]

In [3]:
df["journalist_username"] = df["query_type"].str.extract(r"(@\w+)")
df.head(3)

,tweet_id,username,url,text,image,video,date,reply,retweet,like,...,rt_by,raw,query_type,scraped_at,event,date_cleansed,date_local,dt_date,label,journalist_username
0,1708973726455181497,@soyingridbeck,https://x.com/soyingridbeck/status/17089737264...,Sólo @SergioMassa y @myriambregman abordaron a...,NaN,NaN,2023-10-02T22:34:22+00:00,0,3,17,...,NaN,{'html_tweet': '𝗜𝗻𝗴𝗿𝗶𝗱 𝗕𝗲𝗰𝗸 @soyingridbeck·Oct...,from: @soyingridbeck,2023-10-10T17:43:36.448550+00:00,1er debate,2023-10-02 22:34:22+00:00,2023-10-02 19:34:22-03:00,2023-10-02,[],@soyingridbeck
1,1708809681924243938,@soyingridbeck,https://x.com/soyingridbeck/status/17088096819...,¿Irse a Marbella en un yate de lujo?,NaN,NaN,2023-10-02T11:42:30+00:00,1,0,0,...,NaN,{'html_tweet': '𝗜𝗻𝗴𝗿𝗶𝗱 𝗕𝗲𝗰𝗸 @soyingridbeck·Oct...,from: @soyingridbeck,2023-10-10T17:43:36.612322+00:00,1er debate,2023-10-02 11:42:30+00:00,2023-10-02 08:42:30-03:00,2023-10-02,[],@soyingridbeck
2,1708810804101853498,@kgalperin,https://x.com/kgalperin/status/170881080410185...,"Me asombra esa interpretación, q expresa muy b...",NaN,NaN,2023-10-02T11:46:58+00:00,0,0,1,...,NaN,{'html_tweet': 'Karina Galperin@kgalperin·Oct ...,to: @soyingridbeck,2023-10-10T18:22:43.429345+00:00,1er debate,2023-10-02 11:46:58+00:00,2023-10-02 08:46:58-03:00,2023-10-02,[],@soyingridbeck

In [4]:
mujeres = [
    "@Miglesias71",
    "@gabipellegrini3",
    "@GabrielaWeller",
    "@SanchezClarise",
    "@soyingridbeck",
    "@SilvinaMolina",
    "@mafito11",
    "@AJuliaLopez",
    "@Cris_noticias",
    "@vivicanosaok",
    "@marialauratv",
    "@guadavazquez",
    "@odonnellmaria",
    "@mjolivan",
    "@maclorena",
    "@rominamanguel",
    "@monigps",
    "@lucianageuna",
    "@negropolisok",
    "@juliamengo",
    "@FlorHalfon",
    "@cyngarciaradio",
    "@deboraplager",
    "@silviafbarrio",
    "@NANCYPAZOS",
    "@gabycociffi",
    "@SoleVallejos",
    "@nbg__",
    "@hindelita",
    "@MercedesFunes",
    "@anaecorrea",
    "@Marcelitaojeda",
    "@lucianapeker",
    "@Angelalerena",
]

hombres = [
    "@rialjorge",
    "@fantinofantino",
    "@andykusnetzoff",
    "@SANTIAGODELMORO",
    "@VHMok",
    "@wwnicolas",
    "@edufeiok",
    "@luisnovaresio",
    "@JonatanViale",
    "@majulluis",
    "@barilirodolfo",
    "@diegoleuco",
    "@alfleuco",
    "@Gatosylvestre",
    "@robdnavarro",
    "@Sietecase",
    "@aleberco",
    "@diegobranca",
    "@ischargro",
    "@ertenembaum",
]

print(f"Mujeres periodistas: {len(mujeres)}\nHombres periodistas: {len(hombres)}")

# Check if any element from the lists is present in the 'query_type' column
df["journalist_genre"] = ""
df.loc[df["query_type"].str.contains("|".join(mujeres)), "journalist_genre"] = "M"
df.loc[df["query_type"].str.contains("|".join(hombres)), "journalist_genre"] = "H"

df.head(3)

Mujeres periodistas: 34
Hombres periodistas: 20

,tweet_id,username,url,text,image,video,date,reply,retweet,like,...,raw,query_type,scraped_at,event,date_cleansed,date_local,dt_date,label,journalist_username,journalist_genre
0,1708973726455181497,@soyingridbeck,https://x.com/soyingridbeck/status/17089737264...,Sólo @SergioMassa y @myriambregman abordaron a...,NaN,NaN,2023-10-02T22:34:22+00:00,0,3,17,...,{'html_tweet': '𝗜𝗻𝗴𝗿𝗶𝗱 𝗕𝗲𝗰𝗸 @soyingridbeck·Oct...,from: @soyingridbeck,2023-10-10T17:43:36.448550+00:00,1er debate,2023-10-02 22:34:22+00:00,2023-10-02 19:34:22-03:00,2023-10-02,[],@soyingridbeck,M
1,1708809681924243938,@soyingridbeck,https://x.com/soyingridbeck/status/17088096819...,¿Irse a Marbella en un yate de lujo?,NaN,NaN,2023-10-02T11:42:30+00:00,1,0,0,...,{'html_tweet': '𝗜𝗻𝗴𝗿𝗶𝗱 𝗕𝗲𝗰𝗸 @soyingridbeck·Oct...,from: @soyingridbeck,2023-10-10T17:43:36.612322+00:00,1er debate,2023-10-02 11:42:30+00:00,2023-10-02 08:42:30-03:00,2023-10-02,[],@soyingridbeck,M
2,1708810804101853498,@kgalperin,https://x.com/kgalperin/status/170881080410185...,"Me asombra esa interpretación, q expresa muy b...",NaN,NaN,2023-10-02T11:46:58+00:00,0,0,1,...,{'html_tweet': 'Karina Galperin@kgalperin·Oct ...,to: @soyingridbeck,2023-10-10T18:22:43.429345+00:00,1er debate,2023-10-02 11:46:58+00:00,2023-10-02 08:46:58-03:00,2023-10-02,[],@soyingridbeck,M

In [5]:
df["label"] = df["label"].replace("[]", "")

df.head(3)

,tweet_id,username,url,text,image,video,date,reply,retweet,like,...,raw,query_type,scraped_at,event,date_cleansed,date_local,dt_date,label,journalist_username,journalist_genre
0,1708973726455181497,@soyingridbeck,https://x.com/soyingridbeck/status/17089737264...,Sólo @SergioMassa y @myriambregman abordaron a...,NaN,NaN,2023-10-02T22:34:22+00:00,0,3,17,...,{'html_tweet': '𝗜𝗻𝗴𝗿𝗶𝗱 𝗕𝗲𝗰𝗸 @soyingridbeck·Oct...,from: @soyingridbeck,2023-10-10T17:43:36.448550+00:00,1er debate,2023-10-02 22:34:22+00:00,2023-10-02 19:34:22-03:00,2023-10-02,,@soyingridbeck,M
1,1708809681924243938,@soyingridbeck,https://x.com/soyingridbeck/status/17088096819...,¿Irse a Marbella en un yate de lujo?,NaN,NaN,2023-10-02T11:42:30+00:00,1,0,0,...,{'html_tweet': '𝗜𝗻𝗴𝗿𝗶𝗱 𝗕𝗲𝗰𝗸 @soyingridbeck·Oct...,from: @soyingridbeck,2023-10-10T17:43:36.612322+00:00,1er debate,2023-10-02 11:42:30+00:00,2023-10-02 08:42:30-03:00,2023-10-02,,@soyingridbeck,M
2,1708810804101853498,@kgalperin,https://x.com/kgalperin/status/170881080410185...,"Me asombra esa interpretación, q expresa muy b...",NaN,NaN,2023-10-02T11:46:58+00:00,0,0,1,...,{'html_tweet': 'Karina Galperin@kgalperin·Oct ...,to: @soyingridbeck,2023-10-10T18:22:43.429345+00:00,1er debate,2023-10-02 11:46:58+00:00,2023-10-02 08:46:58-03:00,2023-10-02,,@soyingridbeck,M

In [6]:
df["label"] = df["label"].str.replace("['\[\]]", "", regex=True)

labels = df["label"].to_list()

labels = [x.split(",") for x in labels]

labels = [item for sublist in labels for item in sublist]

labels = [x.lstrip() for x in labels]

labels_count = pd.Series(labels).value_counts()

labels_count

              73999
WOMEN          1859
APPEARANCE     1747
POLITICS       1672
DISABLED        501
RACISM          397
CLASS           251
LGBTI           197
CRIMINAL         78
CALLS            72
Name: count, dtype: int64

In [7]:
labels = [
    "women",
    "politics",
    "appearance",
    "disabled",
    "racism",
    "class",
    "lgbti",
    "criminal",
    "calls",
]

for label in labels:
    df[label] = df["label"].str.contains(label, case=False).astype(int)

df.head(3)

,tweet_id,username,url,text,image,video,date,reply,retweet,like,...,journalist_genre,women,politics,appearance,disabled,racism,class,lgbti,criminal,calls
0,1708973726455181497,@soyingridbeck,https://x.com/soyingridbeck/status/17089737264...,Sólo @SergioMassa y @myriambregman abordaron a...,NaN,NaN,2023-10-02T22:34:22+00:00,0,3,17,...,M,0,0,0,0,0,0,0,0,0
1,1708809681924243938,@soyingridbeck,https://x.com/soyingridbeck/status/17088096819...,¿Irse a Marbella en un yate de lujo?,NaN,NaN,2023-10-02T11:42:30+00:00,1,0,0,...,M,0,0,0,0,0,0,0,0,0
2,1708810804101853498,@kgalperin,https://x.com/kgalperin/status/170881080410185...,"Me asombra esa interpretación, q expresa muy b...",NaN,NaN,2023-10-02T11:46:58+00:00,0,0,1,...,M,0,0,0,0,0,0,0,0,0

In [8]:
df["to_journalist"] = (
    df["query_type"]
    .str.extract(r"(?<=to:\s)(@\w+)", flags=re.IGNORECASE)
    .fillna(np.nan)
)

df.head(3)

,tweet_id,username,url,text,image,video,date,reply,retweet,like,...,women,politics,appearance,disabled,racism,class,lgbti,criminal,calls,to_journalist
0,1708973726455181497,@soyingridbeck,https://x.com/soyingridbeck/status/17089737264...,Sólo @SergioMassa y @myriambregman abordaron a...,NaN,NaN,2023-10-02T22:34:22+00:00,0,3,17,...,0,0,0,0,0,0,0,0,0,NaN
1,1708809681924243938,@soyingridbeck,https://x.com/soyingridbeck/status/17088096819...,¿Irse a Marbella en un yate de lujo?,NaN,NaN,2023-10-02T11:42:30+00:00,1,0,0,...,0,0,0,0,0,0,0,0,0,NaN
2,1708810804101853498,@kgalperin,https://x.com/kgalperin/status/170881080410185...,"Me asombra esa interpretación, q expresa muy b...",NaN,NaN,2023-10-02T11:46:58+00:00,0,0,1,...,0,0,0,0,0,0,0,0,0,@soyingridbeck

In [9]:
df["from_journalist"] = (
    df["query_type"]
    .str.extract(r"(?<=from:\s)(@\w+)", flags=re.IGNORECASE)
    .fillna(np.nan)
)

df.head(3)

,tweet_id,username,url,text,image,video,date,reply,retweet,like,...,politics,appearance,disabled,racism,class,lgbti,criminal,calls,to_journalist,from_journalist
0,1708973726455181497,@soyingridbeck,https://x.com/soyingridbeck/status/17089737264...,Sólo @SergioMassa y @myriambregman abordaron a...,NaN,NaN,2023-10-02T22:34:22+00:00,0,3,17,...,0,0,0,0,0,0,0,0,NaN,@soyingridbeck
1,1708809681924243938,@soyingridbeck,https://x.com/soyingridbeck/status/17088096819...,¿Irse a Marbella en un yate de lujo?,NaN,NaN,2023-10-02T11:42:30+00:00,1,0,0,...,0,0,0,0,0,0,0,0,NaN,@soyingridbeck
2,1708810804101853498,@kgalperin,https://x.com/kgalperin/status/170881080410185...,"Me asombra esa interpretación, q expresa muy b...",NaN,NaN,2023-10-02T11:46:58+00:00,0,0,1,...,0,0,0,0,0,0,0,0,@soyingridbeck,NaN

In [10]:
df["label"] = df["label"].replace("", np.nan)

attacks = df.dropna(subset=["label", "to_journalist"])
attacks.head(3)

,tweet_id,username,url,text,image,video,date,reply,retweet,like,...,politics,appearance,disabled,racism,class,lgbti,criminal,calls,to_journalist,from_journalist
16,1708663701929177449,@adrianacarr,https://x.com/adrianacarr/status/1708663701929...,Me gustan tanto las colaciones Chammas que me ...,NaN,NaN,2023-10-02T02:02:26+00:00,2,0,3,...,0,0,0,0,0,0,0,0,@soyingridbeck,NaN
36,1708654085631512628,@meyscapola,https://x.com/meyscapola/status/17086540856315...,Menos mal que no es facho,NaN,NaN,2023-10-02T01:24:13+00:00,0,0,9,...,1,0,0,0,0,0,0,0,@soyingridbeck,NaN
185,1708976424147734979,@daniel23031774,https://x.com/daniel23031774/status/1708976424...,La tenes adentro tetona,NaN,NaN,2023-10-02T22:45:05+00:00,0,0,0,...,0,0,0,0,0,0,0,0,@vivicanosaok,NaN

In [89]:
df.to_csv("../data/processed/elecciones_argentina.csv", index=False)
attacks.to_excel(
    "../data/processed/ataques_elecciones_argentina.xlsx",
    index=False,
    sheet_name="data",
)